


























/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f45762-0be1ec325e1bf0c415e62d73;73191e21-d937-4a17-9f34-14b01cd4cbd1)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 62.8447, 'train_samples_per_second': 3.501, 'train_steps_per_second': 0.43, 'train_loss': 1.618138489899812, 'epoch': 0.98}
***** train metrics *****
  epoch                    =     0.9818
  total_flos               =  3543966GF
  train_loss               =     1.6181
  train_runtime            = 0:01:02.84
  train_samples            =        220
  train_samples_per_second =      3.501
  train_steps_per_second   =       0.43
15
1.2e-06


























 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████    | 26/27 [00:53<00:02,  2.08s/it]
{'train_runtime': 56.047, 'train_samples_per_second': 3.89, 'train_steps_per_second': 0.482, 'train_loss': 1.6089374400951244, 'epoch': 0.99}
***** train metrics *****
  epoch                    =     0.9908
  total_flos               =  3543966GF
  train_loss               =     1.6089
  train_runtime            = 0:00:56.04
  train_samples            =        218
  train_samples_per_second =       3.89
  train_steps_per_second   =      0.482
16
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f4579b-1849276d6b5ef037033f5a21;9dae4c83-3eba-4351-b7b4-0e36f39fedb1)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(



























 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 27/28 [00:56<00:02,  2.08s/it]
{'train_runtime': 58.3478, 'train_samples_per_second': 3.856, 'train_steps_per_second': 0.48, 'train_loss': 1.6040562220982142, 'epoch': 0.99}
***** train metrics *****
  epoch                    =     0.9912
  total_flos               =  3675224GF
  train_loss               =     1.6041
  train_runtime            = 0:00:58.34
  train_samples            =        225
  train_samples_per_second =      3.856
  train_steps_per_second   =       0.48
15
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f457d7-1da483f855bcc7cb030db375;c73c376a-eaa8-4c62-a961-73d03770b2c7)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(


























/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f45810-62c792fb57f649387bd8f8f0;a8ef99c0-0849-4f86-9575-88cff61274aa)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 56.3608, 'train_samples_per_second': 3.939, 'train_steps_per_second': 0.479, 'train_loss': 1.6154864275896992, 'epoch': 0.97}
***** train metrics *****
  epoch                    =      0.973
  total_flos               =  3543966GF
  train_loss               =     1.6155
  train_runtime            = 0:00:56.36
  train_samples            =        222
  train_samples_per_second =      3.939
  train_steps_per_second   =      0.479
15
1.2e-06


























 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████    | 26/27 [00:54<00:02,  2.09s/it]
{'train_runtime': 56.4035, 'train_samples_per_second': 3.9, 'train_steps_per_second': 0.479, 'train_loss': 1.6285439950448495, 'epoch': 0.98}
***** train metrics *****
  epoch                    =     0.9818
  total_flos               =  3543966GF
  train_loss               =     1.6285
  train_runtime            = 0:00:56.40
  train_samples            =        220
  train_samples_per_second =        3.9
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f4584a-549da0772fe7c2224bea34a8;a4fbc3c4-0ae0-45d4-b9f5-8632f8a8f19c)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(











100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:23<00:00,  1.58it/s]
***** eval metrics *****
  epoch                   =     0.9818
  eval_accuracy           =     0.7423
  eval_invalid_labels     =     244731
  eval_invalid_preds      =     242231
  eval_loss               =     1.5402
  eval_runtime            = 0:00:28.84
  eval_samples            =        251
  eval_samples_per_second =        8.7
  eval_steps_per_second   =      1.109
  eval_total              =      12042
Traceback (most recent call last):█████████████████████████████████████████████████████████████████████████████| 32/32 [00:23<00:00,  1.58it/s]
  File "/data/home/yjw5427/translora/fed_lora.py", line 937, in <module>
  File "/data/home/yjw5427/translora/fed_lora.py", line 864, in main
    print("---------------------------------------------------\n")
KeyError: 'instruction'
Traceback (most recent call last):
  File "/data/home/yjw5427/translora/fed_lora.py", line 937, in <module>
  File "/data/home/yjw5427/translora/fed_lora.py", line 864, in main
    print("---------------------------------------------------\n")
KeyError: 'instruction'