













/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f32274-33f34b2405e2f94969f1af3b;007d292b-3799-4d10-80ac-eee6c16164cc)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 42.7794, 'train_samples_per_second': 2.618, 'train_steps_per_second': 0.327, 'train_loss': 3.4108145577566966, 'epoch': 1.0}
***** train metrics *****
  epoch                    =        1.0
  total_flos               =  1837622GF
  train_loss               =     3.4108
  train_runtime            = 0:00:42.77
  train_samples            =        200
  train_samples_per_second =      2.618
  train_steps_per_second   =      0.327
14
1.2e-06













 93%|███████████████████████████████████████████████████████████████████████████████████████████▉       | 13/14 [00:31<00:02,  2.47s/it]
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f32297-6753046c27aa5f1e621b5602;3ec5fa89-827d-4d30-bdc9-75b034cac145)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                            | 0/14 [00:00<?, ?it/s]
***** train metrics *****
  epoch                    =        1.0
  total_flos               =  1837622GF
  train_loss               =     4.1374
  train_runtime            = 0:00:34.48
  train_samples            =        200
  train_samples_per_second =      3.248
  train_steps_per_second   =      0.406
14













 93%|███████████████████████████████████████████████████████████████████████████████████████████▉       | 13/14 [00:32<00:02,  2.47s/it]
{'train_runtime': 34.6028, 'train_samples_per_second': 3.237, 'train_steps_per_second': 0.405, 'train_loss': 3.7588936941964284, 'epoch': 1.0}
***** train metrics *****
  epoch                    =        1.0
  total_flos               =  1837622GF
  train_loss               =     3.7589
  train_runtime            = 0:00:34.60
  train_samples            =        200
  train_samples_per_second =      3.237
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f322bb-15b8dfaf29ce87bb0074185c;a24556ca-8465-46f1-9ab7-ee9a0a49636c)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                            | 0/14 [00:00<?, ?it/s]
14














100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:34<00:00,  2.47s/it]
{'train_runtime': 34.6725, 'train_samples_per_second': 3.23, 'train_steps_per_second': 0.404, 'train_loss': 3.5550973074776784, 'epoch': 1.0}
***** train metrics *****
  epoch                    =        1.0
  total_flos               =  1837622GF
  train_loss               =     3.5551
  train_runtime            = 0:00:34.67
  train_samples            =        200
  train_samples_per_second =       3.23
  train_steps_per_second   =      0.404
14
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f322df-0bec8d7b50af748f21a4ce5a;bd2eaef4-18c5-4c2d-b974-3bf27ddd833c)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(







  File "/data/home/yjw5427/translora/fed_lora_cls.py", line 891, in <module>                             | 7/14 [00:17<00:17,  2.47s/it]
    main()
  File "/data/home/yjw5427/translora/fed_lora_cls.py", line 749, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
    return inner_training_loop(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 2393, in _inner_training_loop
    and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
KeyboardInterrupt
Traceback (most recent call last):
  File "/data/home/yjw5427/translora/fed_lora_cls.py", line 891, in <module>
    main()
  File "/data/home/yjw5427/translora/fed_lora_cls.py", line 749, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
    return inner_training_loop(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 2393, in _inner_training_loop
    and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
KeyboardInterrupt