
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455c8-4455422b53ef6e1e0bfb76a8;ce6e3f98-32a2-4df2-a94c-fb56329db405)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 9.2874, 'train_samples_per_second': 1.184, 'train_steps_per_second': 0.108, 'train_loss': 1.5746233463287354, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.5746
  train_runtime            = 0:00:09.28
  train_samples            =         11
  train_samples_per_second =      1.184
  train_steps_per_second   =      0.108
0
1.2e-06
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
{'train_runtime': 2.1376, 'train_samples_per_second': 5.614, 'train_steps_per_second': 0.468, 'train_loss': 1.5380908250808716, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.5381
  train_runtime            = 0:00:02.13
  train_samples            =         12
  train_samples_per_second =      5.614
  train_steps_per_second   =      0.468
0
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455cc-24d66934795a905b79c56ab5;8ae85f43-11ea-4a70-8b27-74bc0d1abe13)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455cf-0b6cc9f7116fb05d0bbd7141;6b252068-f78b-413c-b0e2-5be868f6c4a5)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 2.1963, 'train_samples_per_second': 5.008, 'train_steps_per_second': 0.455, 'train_loss': 1.629568338394165, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.6296
  train_runtime            = 0:00:02.19
  train_samples            =         11
  train_samples_per_second =      5.008
  train_steps_per_second   =      0.455
0
1.2e-06
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455d2-7fa1953a6a289ba054464aec;f63a1620-db6a-40d1-94bc-026a7b3e0860)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
{'train_runtime': 2.1219, 'train_samples_per_second': 5.184, 'train_steps_per_second': 0.471, 'train_loss': 1.604989767074585, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =      1.605
  train_runtime            = 0:00:02.12
  train_samples            =         11
  train_samples_per_second =      5.184
  train_steps_per_second   =      0.471
0
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455d5-10eded0d41b5e2136d17ac4c;37d03151-dbdc-44cf-bb42-15212c523c8f)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 2.1437, 'train_samples_per_second': 5.131, 'train_steps_per_second': 0.466, 'train_loss': 1.5724711418151855, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.5725
  train_runtime            = 0:00:02.14
  train_samples            =         11
  train_samples_per_second =      5.131
  train_steps_per_second   =      0.466












100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:23<00:00,  1.61it/s]
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
***** eval metrics *****
  epoch                   =     0.6667
  eval_accuracy           =     0.7414
  eval_invalid_labels     =     244731
  eval_invalid_preds      =     242211
  eval_loss               =     1.5433
  eval_runtime            = 0:00:28.40
  eval_samples            =        251
  eval_samples_per_second =      8.836
  eval_steps_per_second   =      1.127
  eval_total              =      12042
  perplexity              =     4.6801
This round clients: [5, 6, 7, 8, 9]
0
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455f5-22935238213beed714919be3;0c900056-9a41-4081-8be8-6128340b1fa5)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 2.1844, 'train_samples_per_second': 5.036, 'train_steps_per_second': 0.458, 'train_loss': 1.5752441883087158, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.5752
  train_runtime            = 0:00:02.18
  train_samples            =         11
  train_samples_per_second =      5.036
  train_steps_per_second   =      0.458
0
1.8000000000000001e-06
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455f9-2dffe82e230c94a61ad59ff9;0230d749-bc44-4af0-9366-3a90b8fc5c43)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
{'train_runtime': 2.2624, 'train_samples_per_second': 5.304, 'train_steps_per_second': 0.442, 'train_loss': 1.5378042459487915, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.5378
  train_runtime            = 0:00:02.26
  train_samples            =         12
  train_samples_per_second =      5.304
  train_steps_per_second   =      0.442
0
1.8000000000000001e-06
{'train_runtime': 2.1897, 'train_samples_per_second': 5.023, 'train_steps_per_second': 0.457, 'train_loss': 1.6299844980239868, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =       1.63
  train_runtime            = 0:00:02.18
  train_samples            =         11
  train_samples_per_second =      5.023
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455fc-19d544ec17628c8346e85916;3d709f65-9db0-4f78-9d1f-1433ac5a017c)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
0
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f455ff-7f7b9bd963eaa44669215f75;d1d8ecd3-3fa0-4fd8-8c3e-02a57ab1ba78)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 2.1312, 'train_samples_per_second': 5.161, 'train_steps_per_second': 0.469, 'train_loss': 1.6053552627563477, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.6054
  train_runtime            = 0:00:02.13
  train_samples            =         11
  train_samples_per_second =      5.161
  train_steps_per_second   =      0.469
0
1.8000000000000001e-06
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f45602-16f9bfc529b47e223bd01cfc;335d6485-fe0b-4f8b-8aff-c6c51d149221)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                                   | 0/32 [00:00<?, ?it/s]
{'train_runtime': 2.1233, 'train_samples_per_second': 5.181, 'train_steps_per_second': 0.471, 'train_loss': 1.572230339050293, 'epoch': 0.67}
***** train metrics *****
  epoch                    =     0.6667
  total_flos               =   131258GF
  train_loss               =     1.5722
  train_runtime            = 0:00:02.12
  train_samples            =         11
  train_samples_per_second =      5.181


  File "/data/home/yjw5427/translora/fed_lora.py", line 935, in <module>                                        | 8/32 [00:05<00:17,  1.35it/s]
    main()
  File "/data/home/yjw5427/translora/fed_lora.py", line 829, in main
    metrics = trainer.evaluate()
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 3868, in evaluate
    output = eval_loop(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 4079, in evaluation_loop
    labels = self.accelerator.pad_across_processes(labels, dim=1, pad_index=-100)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/accelerator.py", line 2595, in pad_across_processes
    return pad_across_processes(tensor, dim=dim, pad_index=pad_index, pad_first=pad_first)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 412, in wrapper
    return function(*args, **kwargs)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 682, in pad_across_processes
    return recursively_apply(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 127, in recursively_apply
    return func(data, *args, **kwargs)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 662, in _pad_across_processes
    size = torch.tensor(tensor.shape, device=tensor.device)[None]
KeyboardInterrupt
Traceback (most recent call last):
  File "/data/home/yjw5427/translora/fed_lora.py", line 935, in <module>
    main()
  File "/data/home/yjw5427/translora/fed_lora.py", line 829, in main
    metrics = trainer.evaluate()
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 3868, in evaluate
    output = eval_loop(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 4079, in evaluation_loop
    labels = self.accelerator.pad_across_processes(labels, dim=1, pad_index=-100)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/accelerator.py", line 2595, in pad_across_processes
    return pad_across_processes(tensor, dim=dim, pad_index=pad_index, pad_first=pad_first)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 412, in wrapper
    return function(*args, **kwargs)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 682, in pad_across_processes
    return recursively_apply(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 127, in recursively_apply
    return func(data, *args, **kwargs)
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/accelerate/utils/operations.py", line 662, in _pad_across_processes
    size = torch.tensor(tensor.shape, device=tensor.device)[None]
KeyboardInterrupt